---
- hosts: kvnode,vznode
  remote_user: root
  tasks:
  - name: install freeipmi
    yum:
      name: freeipmi
      state: latest
  - name: install openpmi
    yum:
      name: openipmi
      state: latest


