---
- hosts: webhost
  remote_user: root
  tasks:
  - name: Check for local.php.ini
    local_action: stat path=/srv/config/php.ini get_md5=yes
    register: lmd5
  - stat: path=/etc/php.ini get_md5=yes
    register: rmd5
  - local_action: shell /opt/tools/sh/sshdiff.sh {{ ansible_nodename }} /etc/php.ini /srv/configs/php.ini
    register: diffdata
    when: "'{{lmd5.stat.md5}}' != '{{rmd5.stat.md5}}'"
