---
- hosts: vmmgr
#  gather_facts: no
  tasks:
    - name: Check for list of user
      shell: /usr/local/mgr5/sbin/mgrctl -m vmmgr user |grep -v level=16 |sed 's/.*name=//'  |egrep -v '^admin |artem |^shtnik |^sasga |^asgard |billmgr |^bunkerbill |^stemenev |scherbak |v.chernyshov |^i.artemev |^a.adushkin |^k.tsvetkov |^d.bahaev |^jammarra |^ddosguard |belov |^s.temenev '
      register: oout
      ignore_errors: true

    - name: send message
    #debug: msg={{ oout }}
      local_action: shell /opt/tools/sh/sendme.sh {{ ansible_nodename }} "{{ oout.stdout}} "
      when: not oout|failed 
