---
- hosts: webhost
  remote_user: root
  tasks:
  - name: Check for proftpd.conf
    local_action: stat path=/opt/configs/proftpd.conf get_md5=yes
    register: lmd5
  - stat: path=/etc/proftpd.conf get_md5=yes
    register: rmd5
  - local_action: shell /opt/tools/sh/sshdiff.sh {{ ansible_nodename }} /etc/proftpd.conf /opt/configs/proftpd.conf
    register: diffdata
    when: "'{{lmd5.stat.md5}}' != '{{rmd5.stat.md5}}'"
