---
- hosts: database
  # Playbook for install mysql (mariadb) at Centos 7 run ansible-playbook mysqlNode.yml --extra-vars "mysql_root_password=Secret_Pass"
  tasks:
    - name: Install MySQL
      action: yum name={{item}}
      with_items:
        - mariadb.x86_64
        - mariadb-server.x86_64
        - MySQL-python.x86_64

    - name: copy my.cnf file with root password credentials
      template: src=/opt/configs/myserver.cnf.j2 dest=/etc/my.cnf owner=root mode=0600

    - name: Start the MySQL service
      action: service name=mariadb state=started

    - name: update mysql root password for all root accounts
      mysql_user: name=root host={{ item }} password={{ mysql_root_password }}
      with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost

    - name: copy .my.cnf file with root password credentials
      template: src=/opt/configs/my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

    - name: delete anonymous MySQL server user for {{ ansible_hostname }}
      action: mysql_user user="" host="{{ ansible_hostname }}" state="absent"

    - name: delete anonymous MySQL server user for localhost
      action: mysql_user user="" state="absent"

    - name: remove the MySQL test database
      action: mysql_db db=test state=absent

